name: Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node deps
        run: npm ci

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Restore Allure history (optional)
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: previous-allure-report
        continue-on-error: true

      - name: Copy history into new results
        run: |
          if [ -d "previous-allure-report/history" ]; then
            echo "History found â†’ copying..."
            mkdir -p allure-results/history
            cp -R previous-allure-report/history/* allure-results/history/
          else
            echo "No previous history"
          fi

      - name: Run Playwright tests
        run: npx playwright test --reporter=line,allure-playwright

      - name: Generate Allure Report
        run: |
          allure generate allure-results --clean
          ls -la allure-report

      - name: Upload Allure Report (for history next run)
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report

      - name: Upload Allure Results (raw)
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Deploy Allure Report to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          publish_branch: gh-pages
